#GENERALES
spring.config.import=optional:file:.env[.properties]
spring.application.name=D'Vita
spring.datasource.url=jdbc:mysql://localhost:3306/dvita
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always

#API RENIEC
reniec.api.url=https://api.reniec.gob.pe
reniec.api.token=tu_token_aqui

#GMAIL SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juniorfernandozumaetagolac@gmail.com
spring.mail.password=tu_app_password_aqui
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true